<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $catChampagne = Category::where('slug', 'vip-sampanya-sise-servisi')->first();
        $catCocktail = Category::where('slug', 'imza-kokteyller-miksoloji')->first();
        $catWhisky = Category::where('slug', 'single-malt-nadir-viskiler')->first();
        $catSpirit = Category::where('slug', 'ultra-premium-ickiler')->first();
        $catShots = Category::where('slug', 'shot-tepsileri-bomb-setleri')->first();
        $catWine = Category::where('slug', 'luks-saraplar-kopukluler')->first();
        $catHookah = Category::where('slug', 'artisan-vip-nargile')->first();
        $catFood = Category::where('slug', 'vip-lounge-atistirmaliklari')->first();

        $products = [
            [
                'category_id' => $catChampagne->id,
                'name' => 'Dom Pérignon Vintage Brut',
                'sub_title' => 'Vintage 2013 | Épernay Prestige Cuvée',
                'description' => 'Taze briyoş, beyaz şeftali, narenciye ve ipeksi mineral dokunuşlarla gecenin vazgeçilmez VIP ritüeli.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Taze Briyoş, Beyaz Şeftali, Kireçtaşı Minerali',
                'price' => 28500.00,
                'original_price' => 32000.00,
                'badge' => 'VIP ICON',
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Armand de Brignac Ace of Spades Gold',
                'sub_title' => 'Brut Gold | Altın Kaplama Özel Şişe',
                'description' => 'Kremalı tereyağı, pişmiş elma, vanilya ve pürüzsüz altın kabarcıklar içeren dünya çapında ikonik şampanya.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Pişmiş Elma, Vanilya Çubuğu, Tereyağlı Briyoş',
                'price' => 45000.00,
                'original_price' => 50000.00,
                'badge' => 'PRESTIGE',
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Louis Roederer Cristal Brut',
                'sub_title' => 'Millésimé 2014 | Düz Tabana Sahip Kristal Şişe',
                'description' => 'Beyaz çiçekler, kavrulmuş fındık, kireçtaşı mineralliği ve narin narenciye kabuğu zarafeti.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'taste_notes' => 'Akasya Çiçeği, Fındık, Narenciye Kabuğu',
                'price' => 42000.00,
                'original_price' => 46000.00,
                'badge' => 'RARE',
                'is_featured' => true,
                'sort_order' => 3,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Moët & Chandon Impérial Brut',
                'sub_title' => 'Brut Réserve | Fransa',
                'description' => 'Yeşil elma, sarı armut, narenciye tazeliği ve taze ceviz notalarıyla dengeli ve canlı bir kutlama içeceği.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'taste_notes' => 'Yeşil Elma, Armut, Taze Ceviz',
                'price' => 12500.00,
                'original_price' => 14000.00,
                'badge' => 'BESTSELLER',
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Moët & Chandon Ice Impérial',
                'sub_title' => 'Buz Üzerinde Servis Edilen Özel Seri',
                'description' => 'Buzla ve taze nane veya kırmızı meyvelerle servis edilen tropikal meyve, mango, guava ve zencefil harmanı.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'taste_notes' => 'Mango, Guava, Taze Zencefil, Nane',
                'price' => 14500.00,
                'original_price' => 16500.00,
                'badge' => 'SUMMER VIP',
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Veuve Clicquot Yellow Label Brut',
                'sub_title' => 'Reims | Güçlü Pinot Noir Hakimiyeti',
                'description' => 'Vanilya, olgun armut, kavrulmuş badem ve sağlam gövdesiyle gece clublarının klasik tercihi.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.0,
                'taste_notes' => 'Kavrulmuş Badem, Olgun Armut, Vanilya',
                'price' => 13500.00,
                'original_price' => 15000.00,
                'badge' => 'CLASSIC',
                'is_featured' => false,
                'sort_order' => 6,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Dom Pérignon Rosé Luminous',
                'sub_title' => 'Karanlıkta Parlayan LED Tabanlı Özel Şişe',
                'description' => 'Yabani çilek, kuru incir ve füme baharat notaları içeren, masada parlayan lüks pembe şampanya.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Yabani Çilek, İncir, Füme Baharat',
                'price' => 48000.00,
                'original_price' => 54000.00,
                'badge' => 'LUMINOUS',
                'is_featured' => true,
                'sort_order' => 7,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Krug Grande Cuvée 171st Edition',
                'sub_title' => '10 Farklı Yıldan 120 Şarabın Harmanı',
                'description' => 'Kavrulmuş badem, nuga, zencefilli kurabiye ve derin zenginlik sunan dünyanın en prestijli şampanyası.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Nuga, Zencefilli Kurabiye, Badem',
                'price' => 36000.00,
                'original_price' => 40000.00,
                'badge' => 'CONNOISSEUR',
                'is_featured' => false,
                'sort_order' => 8,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Ruinart Blanc de Blancs',
                'sub_title' => '%100 Premier Cru Chardonnay',
                'description' => 'Dünyanın en eski şampanya evinden beyaz şeftali, yasemin çiçeği ve nane ferahlığıyla saf zarafet.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Beyaz Şeftali, Yasemin, Taze Nane',
                'price' => 18500.00,
                'original_price' => 21000.00,
                'badge' => 'REFINED',
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'category_id' => $catChampagne->id,
                'name' => 'Perrier-Jouët Belle Epoque Brut',
                'sub_title' => 'Épernay | Çiçek Motifli Sanat Eseri Şişe',
                'description' => 'Akasya balı, taze zencefil ve beyaz erik aromalarıyla bezeli olağanüstü dengeli bir şampanya.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Akasya Balı, Beyaz Erik, Zencefil',
                'price' => 29500.00,
                'original_price' => 33000.00,
                'badge' => 'EXCLUSIVE',
                'is_featured' => false,
                'sort_order' => 10,
            ],

            [
                'category_id' => $catCocktail->id,
                'name' => 'Midnight Obsidian Smoke',
                'sub_title' => 'Tütsülü Mezkal & Aktif Karbon Reçetesi',
                'description' => 'İsli Oaxacan mezkali, aktif karbon likörü, taze lime suyu, organik agave ve tütsülenmiş biberiye dalı.',
                'volume_ml' => 220,
                'alcohol_percentage' => 18.5,
                'taste_notes' => 'Tütsü, Biberiye, Taze Lime, İsli Agave',
                'price' => 950.00,
                'original_price' => 1100.00,
                'badge' => 'SIGNATURE',
                'is_featured' => true,
                'sort_order' => 11,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Golden Velvet Royale',
                'sub_title' => '24K Yenilebilir Altın Varaklı Şampanya Kokteyli',
                'description' => 'Hennessy VSOP konyak, passion fruit püresi, el yapımı vanilya şurubu ve Moët Brut şampanya köpüğü.',
                'volume_ml' => 200,
                'alcohol_percentage' => 16.0,
                'taste_notes' => 'Çarkıfelek Meyvesi, Vanilya, Altın Köpük',
                'price' => 1100.00,
                'original_price' => 1300.00,
                'badge' => 'LUXURY',
                'is_featured' => true,
                'sort_order' => 12,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Truffle Smoked Old Fashioned',
                'sub_title' => 'Trüf Mantarı İnfüzyonlu Meşe Dumanı',
                'description' => 'Woodford Reserve bourbon viski, trüf özü, organik akçaağaç şurubu, angostura ve kiraz dumanı.',
                'volume_ml' => 180,
                'alcohol_percentage' => 28.0,
                'taste_notes' => 'Trüf Mantarı, Meşe Ağacı, Karamel, Portakal Kabuğu',
                'price' => 1050.00,
                'original_price' => 1200.00,
                'badge' => 'CRAFT',
                'is_featured' => true,
                'sort_order' => 13,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Tokyo Sakura Cloud',
                'sub_title' => 'Roku Gin & Yuzu Sakura Köpüğü',
                'description' => 'Japon Gini Roku, liçi likörü, taze yuzu suyu ve kadifemsi sakura çayı aromalı moleküler köpük.',
                'volume_ml' => 220,
                'alcohol_percentage' => 15.5,
                'taste_notes' => 'Sakura Çiçeği, Liçi, Yuzu Narenciyesi',
                'price' => 900.00,
                'original_price' => 1050.00,
                'badge' => 'EXOTIC',
                'is_featured' => false,
                'sort_order' => 14,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Spicy Passion Dragon',
                'sub_title' => 'Chili İnfüzyonlu Reposado Tekila',
                'description' => 'Acı biber infüzyonlu tekila, taze çarkıfelek meyvesi, ejder meyvesi püresi ve tütsülü lav tuzu kenarı.',
                'volume_ml' => 240,
                'alcohol_percentage' => 17.0,
                'taste_notes' => 'Chili Acılığı, Tropikal Passion, Lav Tuzu',
                'price' => 850.00,
                'original_price' => 950.00,
                'badge' => 'POPULAR',
                'is_featured' => false,
                'sort_order' => 15,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Espresso Velvet Martini',
                'sub_title' => 'Single-Origin Etiyopya Espresso & Beluga',
                'description' => 'Beluga votka, taze çekilmiş single-origin espresso, Kahlúa kahve likörü ve Belçika bitter kakao tozu.',
                'volume_ml' => 180,
                'alcohol_percentage' => 20.0,
                'taste_notes' => 'Koyu Espresso, Bitter Çikolata, İpeksi Krema',
                'price' => 850.00,
                'original_price' => 980.00,
                'badge' => 'AFTER DARK',
                'is_featured' => false,
                'sort_order' => 16,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Basil & Cucumber Smash',
                'sub_title' => 'Hendrick\'s Gin & Mürver Çiçeği',
                'description' => 'Hendrick\'s cin, taze ezilmiş fesleğen yaprakları, salatalık şerbeti, St-Germain ve premium tonik.',
                'volume_ml' => 240,
                'alcohol_percentage' => 14.5,
                'taste_notes' => 'Taze Fesleğen, Salatalık, Mürver Çiçeği',
                'price' => 800.00,
                'original_price' => 900.00,
                'badge' => 'REFRESHING',
                'is_featured' => false,
                'sort_order' => 17,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Dark Nebula Blackberry Sour',
                'sub_title' => 'Böğürtlen & Burbon Kadife Köpük',
                'description' => 'Böğürtlen infüzyonlu viski, ev yapımı ekşi karışım, organik agave ve pürüzsüz vegan köpük tabakası.',
                'volume_ml' => 200,
                'alcohol_percentage' => 17.5,
                'taste_notes' => 'Orman Meyveleri, Ekşi Narenciye, İpeksi Köpük',
                'price' => 880.00,
                'original_price' => 1000.00,
                'badge' => 'SMOOTH',
                'is_featured' => false,
                'sort_order' => 18,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Coconut Cloud Negroni',
                'sub_title' => 'Hindistan Cevizi Yağlı Campari & Tanqueray 10',
                'description' => 'Hindistan cevizi yağıyla yıkanmış Campari, Tanqueray No. Ten, tatlı kırmızı vermut ve portakal esansı.',
                'volume_ml' => 180,
                'alcohol_percentage' => 24.0,
                'taste_notes' => 'Hindistan Cevizi, Acı-Tatlı Portakal, Botanik Ardıç',
                'price' => 920.00,
                'original_price' => 1050.00,
                'badge' => 'TWIST',
                'is_featured' => false,
                'sort_order' => 19,
            ],
            [
                'category_id' => $catCocktail->id,
                'name' => 'Royal French 75',
                'sub_title' => 'The Botanist Gin & Moët Brut Şampanya',
                'description' => 'The Botanist Islay cin, taze limon suyu, şeker kamışı şurubu ve üstüne eklenen Moët Brut şampanya.',
                'volume_ml' => 190,
                'alcohol_percentage' => 16.5,
                'taste_notes' => 'Limon Çiçeği, Canlı Köpük, Botanik Zarafet',
                'price' => 980.00,
                'original_price' => 1150.00,
                'badge' => 'ELEGANT',
                'is_featured' => false,
                'sort_order' => 20,
            ],

            [
                'category_id' => $catWhisky->id,
                'name' => 'The Macallan 18 Double Cask',
                'sub_title' => 'Single Malt Scotch Whisky | Speyside',
                'description' => 'Kuru meyve, zencefil, vanilya, zengin meşe ve pürüzsüz portakal kabuğu notalarıyla viskinin zirvesi.',
                'volume_ml' => 700,
                'alcohol_percentage' => 43.0,
                'taste_notes' => 'Kuru Meyve, Zencefil, Şeri Meşesi, Portakal Kabuğu',
                'price' => 32000.00,
                'original_price' => 36000.00,
                'badge' => 'SINGLE MALT',
                'is_featured' => true,
                'sort_order' => 21,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'The Macallan 12 Sherry Oak',
                'sub_title' => 'Single Malt Scotch Whisky | Jerez Cask',
                'description' => 'Kuru üzüm, tarçın, fındık ve zengin şeri fıçısı aromaları içeren ikonik İskoç lezzeti.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Kuru Üzüm, Tarçın, Şeri, Kavrulmuş Fındık',
                'price' => 14000.00,
                'original_price' => 16000.00,
                'badge' => 'POPULAR',
                'is_featured' => false,
                'sort_order' => 22,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Yamazaki 12 Japanese Single Malt',
                'sub_title' => 'Suntory Whisky | Japonya',
                'description' => 'Mizunara Japon meşesi, şeftali, ananas, hindistan cevizi ve ipeksi uzun bitiş sunan nadir viski.',
                'volume_ml' => 700,
                'alcohol_percentage' => 43.0,
                'taste_notes' => 'Mizunara Meşesi, Şeftali, Ananas, Sandal Ağacı',
                'price' => 34000.00,
                'original_price' => 39000.00,
                'badge' => 'RARE JAPANESE',
                'is_featured' => true,
                'sort_order' => 23,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Hibiki Japanese Harmony',
                'sub_title' => "Master's Blend | 24 Köşeli Özel Şişe",
                'description' => 'Gül yaprağı, liçi, biberiye, olgun meşe ve sandal ağacı zarafetini buluşturan Japon harmoni viskisi.',
                'volume_ml' => 700,
                'alcohol_percentage' => 43.0,
                'taste_notes' => 'Gül, Liçi, Sandal Ağacı, Bal',
                'price' => 22000.00,
                'original_price' => 25000.00,
                'badge' => 'HARMONY',
                'is_featured' => false,
                'sort_order' => 24,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Lagavulin 16 Islay Single Malt',
                'sub_title' => '16 Years Old | Islay İskoçya',
                'description' => 'Yoğun turba dumanı, deniz tuzu, iyot, kuru meyve ve tatlı meşe fıçısı etkisiyle turba tutkunlarının gözdesi.',
                'volume_ml' => 700,
                'alcohol_percentage' => 43.0,
                'taste_notes' => 'Yoğun Turba Dumanı, İyot, Deniz Tuzu, Kuru Meyve',
                'price' => 16500.00,
                'original_price' => 19000.00,
                'badge' => 'SMOKY KING',
                'is_featured' => false,
                'sort_order' => 25,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Johnnie Walker Blue Label',
                'sub_title' => 'Rare Cask Blend | İskoçya',
                'description' => '10.000 fıçıdan sadece 1 tanesinin seçilmesiyle üretilen fındık, bal, gül ve ipeksi duman harmanı.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Bal, Fındık, Gül Yaprakları, İpeksi Duman',
                'price' => 24000.00,
                'original_price' => 27000.00,
                'badge' => 'ICONIC',
                'is_featured' => false,
                'sort_order' => 26,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Glenfiddich 18 Small Batch',
                'sub_title' => 'Oloroso Sherry & Bourbon Casks',
                'description' => 'Fırınlanmış elma, tarçın, kuru meyve ve sağlam İspanyol meşesi içeren 18 yıllık olgunlaşma.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Fırın Elma, Tarçın, İspanyol Meşesi',
                'price' => 15500.00,
                'original_price' => 17500.00,
                'badge' => 'SMOOTH',
                'is_featured' => false,
                'sort_order' => 27,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Balvenie 14 Caribbean Cask',
                'sub_title' => 'Karayip Rom Fıçısında Bitiş',
                'description' => 'Karayip rom fıçılarında son dokunuşu yapılan tatlı tropikal meyve, vanilya ve tofi aromalı single malt.',
                'volume_ml' => 700,
                'alcohol_percentage' => 43.0,
                'taste_notes' => 'Tropikal Meyve, Tofi, Sıcak Rom Baharatı',
                'price' => 16000.00,
                'original_price' => 18000.00,
                'badge' => 'SPECIAL CASK',
                'is_featured' => false,
                'sort_order' => 28,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Talisker 10 Skye Single Malt',
                'sub_title' => 'Made by the Sea | Isle of Skye',
                'description' => 'Deniz tuzu serpintisi, taze çekilmiş karabiber, kuru meyve ve volkanik duman karakteri.',
                'volume_ml' => 700,
                'alcohol_percentage' => 45.8,
                'taste_notes' => 'Karabiber, Deniz Tuzu, Volkanik Duman',
                'price' => 11500.00,
                'original_price' => 13000.00,
                'badge' => 'ISLAND',
                'is_featured' => false,
                'sort_order' => 29,
            ],
            [
                'category_id' => $catWhisky->id,
                'name' => 'Woodford Reserve Double Oaked',
                'sub_title' => 'Kentucky Straight Bourbon Whiskey',
                'description' => 'Çift fırınlanmış meşe fıçılarda dinlendirilen yoğun karamel, kavrulmuş fındık ve bitter çikolata notaları.',
                'volume_ml' => 700,
                'alcohol_percentage' => 43.2,
                'taste_notes' => 'Karamel, Kavrulmuş Fındık, Bitter Çikolata',
                'price' => 11000.00,
                'original_price' => 12500.00,
                'badge' => 'PREMIUM BOURBON',
                'is_featured' => false,
                'sort_order' => 30,
            ],

            [
                'category_id' => $catSpirit->id,
                'name' => 'Clase Azul Reposado Tequila',
                'sub_title' => 'El Yapımı İkonik Seramik Şişe',
                'description' => '%100 Blue Weber Agave, vanilya, fındık, pişmiş agave ve karamel zenginliği ile dünyanın en ünlü tekilası.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Vanilya, Fındık, Pişmiş Agave, Karamel',
                'price' => 38000.00,
                'original_price' => 42000.00,
                'badge' => 'ULTRA VIP',
                'is_featured' => true,
                'sort_order' => 31,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Don Julio 1942 Añejo Tequila',
                'sub_title' => 'Jalisco Meksika | 2.5 Yıl Dinlendirilmiş',
                'description' => 'Meşe fıçıda dinlendirilen sıcak meşe, vanilya, kavrulmuş agave ve meşe aromalarıyla club gecelerinin favorisi.',
                'volume_ml' => 700,
                'alcohol_percentage' => 38.0,
                'taste_notes' => 'Sıcak Meşe, Vanilya, Kavrulmuş Agave',
                'price' => 36000.00,
                'original_price' => 40000.00,
                'badge' => 'CELEBRITY CHOICE',
                'is_featured' => true,
                'sort_order' => 32,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Patrón El Cielo Tequila',
                'sub_title' => 'Dört Kez Damıtılmış Prestige Silver',
                'description' => 'Dört kez damıtılmış gümüş tekila, ultra pürüzsüz içim, narenciye tazeliği ve doğal agave tatlılığı.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Parlak Narenciye, Tatlı Agave, Kristal Saflık',
                'price' => 26000.00,
                'original_price' => 29000.00,
                'badge' => 'PURE SILVER',
                'is_featured' => false,
                'sort_order' => 33,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Beluga Gold Line Vodka',
                'sub_title' => 'Özel Çekiçli Mühürlü Kutu',
                'description' => '90 gün dinlendirilmiş, pirinç ve yabani gül infüzyonlu ultra premium lüks votka deneyimi.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Pirinç Özü, Yabani Gül, Kadife Pürüzsüzlük',
                'price' => 19500.00,
                'original_price' => 22000.00,
                'badge' => 'GOLD LINE',
                'is_featured' => false,
                'sort_order' => 34,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Grey Goose VX Exceptional Vodka',
                'sub_title' => 'Fransız Konyak Damlaları ile Zenginleştirilmiş',
                'description' => 'Fransız buğday votkasının nadir Grand Champagne konyak damlalarıyla harmanlandığı lüks şişe.',
                'volume_ml' => 1000,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Konyak Nüansı, Erik, Beyaz Meyve, İpek Doku',
                'price' => 14500.00,
                'original_price' => 16500.00,
                'badge' => 'FRENCH LUXURY',
                'is_featured' => false,
                'sort_order' => 35,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Belvedere 10 Rare Single Estate',
                'sub_title' => '10 Adımlık Üretim & Elmas Kesim Şişe',
                'description' => 'Tek bir hasattan elde edilen organik elmas çavdarı, bal, yeşil elma ve kremsi doku.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Yeşil Elma, Bal, Vanilya Kreması',
                'price' => 22000.00,
                'original_price' => 25000.00,
                'badge' => 'LIMITED',
                'is_featured' => false,
                'sort_order' => 36,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Monkey 47 Schwarzwald Dry Gin',
                'sub_title' => 'Almanya Kara Orman | 47 Botanik',
                'description' => 'Kara Orman kaynak suyu ve 47 farklı botanik bitki, ardıç, böğürtlen, limon otu ve egzotik baharatlar.',
                'volume_ml' => 500,
                'alcohol_percentage' => 47.0,
                'taste_notes' => 'Ardıç, Böğürtlen, Limon Otu, Çam Esansı',
                'price' => 8500.00,
                'original_price' => 9500.00,
                'badge' => 'BOTANICAL',
                'is_featured' => false,
                'sort_order' => 37,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'The Botanist Islay Dry Gin',
                'sub_title' => 'Islay İskoçya | 22 Yabani Ada Bitkisi',
                'description' => 'Islay adasından elle toplanan 22 yabani ada bitkisiyle damıtılmış çiçeksi ve tazeleyici cin.',
                'volume_ml' => 700,
                'alcohol_percentage' => 46.0,
                'taste_notes' => 'Yabani Nane, Papatya, Ardıç, Narenciye',
                'price' => 9500.00,
                'original_price' => 11000.00,
                'badge' => 'ARTISAN',
                'is_featured' => false,
                'sort_order' => 38,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Zacapa 23 Solera Gran Reserva',
                'sub_title' => 'Guatemala | Deniz Seviyesinden 2300m Yüksekte',
                'description' => 'Solera sistemiyle yıllandırılmış bal, karamel, kurutulmuş meyve, meşe ve kakao zenginliği.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Karamel, Kuru İncir, Kakao, Meşe',
                'price' => 13500.00,
                'original_price' => 15000.00,
                'badge' => 'SOLERA RUM',
                'is_featured' => false,
                'sort_order' => 39,
            ],
            [
                'category_id' => $catSpirit->id,
                'name' => 'Hennessy XO Extra Old Cognac',
                'sub_title' => '100 Farklı Eaux-de-Vie Harmanı',
                'description' => 'Karabiber, kuru incir, kakao, tütün yaprağı ve deri dokunuşlarıyla efsanevi Fransız konyak başyapıtı.',
                'volume_ml' => 700,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Karabiber, Kuru İncir, Kakao, Deri',
                'price' => 28000.00,
                'original_price' => 32000.00,
                'badge' => 'PRESTIGE COGNAC',
                'is_featured' => true,
                'sort_order' => 40,
            ],

            [
                'category_id' => $catShots->id,
                'name' => 'Golden Tequila VIP Tray (6 Shots)',
                'sub_title' => '6 Adet Don Julio Blanco & Altın Tuzu',
                'description' => 'Don Julio Blanco, tuzlanmış 24K altın pulları, taze portakal ve tarçın dilimleri ile servis edilen VIP tepsi.',
                'volume_ml' => 240,
                'alcohol_percentage' => 38.0,
                'taste_notes' => 'Saf Agave, Tarçınlı Portakal, Altın Tuzu',
                'price' => 2400.00,
                'original_price' => 2800.00,
                'badge' => 'PARTY TRAY',
                'is_featured' => true,
                'sort_order' => 41,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'B-52 Flaming Layered Shots (4 Shots)',
                'sub_title' => '4 Adet 3 Katmanlı Alevli Shot',
                'description' => 'Kahlúa kahve likörü, Baileys Irish Cream ve Grand Marnier ile 3 katmanlı alevli shot seremonisi.',
                'volume_ml' => 160,
                'alcohol_percentage' => 28.0,
                'taste_notes' => 'Kahve, Krema, Portakal Likörü, Karamel',
                'price' => 1800.00,
                'original_price' => 2100.00,
                'badge' => 'FLAMING',
                'is_featured' => false,
                'sort_order' => 42,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Jägerbomb Energy Blast Set (4 Shots)',
                'sub_title' => '4 Adet Jägermeister & Red Bull',
                'description' => 'Orijinal Jägermeister shot kadehinin buz gibi Red Bull kadehine bırakıldığı yüksek enerjili club klasiği.',
                'volume_ml' => 360,
                'alcohol_percentage' => 25.0,
                'taste_notes' => 'Bitkisel Baharatlar, Enerji, Anason, Narenciye',
                'price' => 1900.00,
                'original_price' => 2200.00,
                'badge' => 'HIGH ENERGY',
                'is_featured' => true,
                'sort_order' => 43,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Kamikaze Citrus Burst Tray (6 Shots)',
                'sub_title' => '6 Adet Votka & Cointreau Shot',
                'description' => 'Premium votka, Cointreau portakal likörü ve taze sıkılmış misket limonu suyu ile buz gibi ferahlık.',
                'volume_ml' => 240,
                'alcohol_percentage' => 22.0,
                'taste_notes' => 'Misket Limonu, Portakal Kabuğu, Canlı Asidite',
                'price' => 1950.00,
                'original_price' => 2300.00,
                'badge' => 'CRISP',
                'is_featured' => false,
                'sort_order' => 44,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Silver Bullet Mezcal Tray (6 Shots)',
                'sub_title' => '6 Adet Tütsülü Mezkal & Passion',
                'description' => 'Oaxacan tütsülü mezkal, tütsülü lav tuzu ve taze çarkıfelek meyvesi dilimleri eşliğinde servis.',
                'volume_ml' => 240,
                'alcohol_percentage' => 40.0,
                'taste_notes' => 'Tütsü Dumanı, Çarkıfelek Meyvesi, Lav Tuzu',
                'price' => 2600.00,
                'original_price' => 3000.00,
                'badge' => 'SMOKY SHOTS',
                'is_featured' => false,
                'sort_order' => 45,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Lemon Drop Sugar Rim Set (6 Shots)',
                'sub_title' => '6 Adet Şeker Kenarlı Limon Shot',
                'description' => 'Absolut Citron votka, Limoncello, karamelize esmer şeker kenarlığı ve taze narenciye dilimi.',
                'volume_ml' => 240,
                'alcohol_percentage' => 20.0,
                'taste_notes' => 'Tatlı Limon Şekeri, Taze Narenciye',
                'price' => 1850.00,
                'original_price' => 2100.00,
                'badge' => 'SWEET & SOUR',
                'is_featured' => false,
                'sort_order' => 46,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Brain Hemorrhage Visual Set (4 Shots)',
                'sub_title' => '4 Adet Görsel Efektli Katman Shot',
                'description' => 'Şeftali schnapps üzerine Baileys krema damlaları ve kan kırmızısı grenadin damlatılarak hazırlanan görsel şov.',
                'volume_ml' => 160,
                'alcohol_percentage' => 18.0,
                'taste_notes' => 'Şeftali, İrlanda Kreması, Tatlı Nar',
                'price' => 1700.00,
                'original_price' => 2000.00,
                'badge' => 'VISUAL EFFECT',
                'is_featured' => false,
                'sort_order' => 47,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Black Absinthe Devil Tray (4 Shots)',
                'sub_title' => '4 Adet Siyah Absent & Alevli Şeker',
                'description' => '%55 alkollü siyah pelin otu absenti, anason esansı ve kaşıkta alevle karamelize edilmiş kesme şeker.',
                'volume_ml' => 160,
                'alcohol_percentage' => 55.0,
                'taste_notes' => 'Güçlü Anason, Pelin Otu, Karamelize Şeker',
                'price' => 2800.00,
                'original_price' => 3200.00,
                'badge' => 'EXTREME',
                'is_featured' => false,
                'sort_order' => 48,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Baby Guinness Mini Stout (6 Shots)',
                'sub_title' => '6 Adet Kahve & Krema Mini Stout',
                'description' => 'Tía María kahve likörü üzerine dökülen Baileys krema köpüğü ile minyatür siyah bira görünümü.',
                'volume_ml' => 240,
                'alcohol_percentage' => 20.0,
                'taste_notes' => 'Yoğun Kahve, İpeksi Krema, Vanilya',
                'price' => 1900.00,
                'original_price' => 2200.00,
                'badge' => 'CREAMY',
                'is_featured' => false,
                'sort_order' => 49,
            ],
            [
                'category_id' => $catShots->id,
                'name' => 'Godfather Nightcap Tray (4 Shots)',
                'sub_title' => '4 Adet İskoç Viskisi & Disaronno',
                'description' => 'Single malt İskoç viskisi ve otantik İtalyan badem likörü Disaronno ile güçlü ve tatlı shot ritüeli.',
                'volume_ml' => 160,
                'alcohol_percentage' => 32.0,
                'taste_notes' => 'İskoç Meşesi, Acıbadem, Kayısı Çekirdeği',
                'price' => 1950.00,
                'original_price' => 2300.00,
                'badge' => 'STRONG',
                'is_featured' => false,
                'sort_order' => 50,
            ],

            [
                'category_id' => $catWine->id,
                'name' => 'Château Margaux Premier Grand Cru',
                'sub_title' => 'Bordeaux Margaux | Fransa 2015',
                'description' => 'Bordeaux\'nun efsanevi başyapıtı; menekşe çiçeği, siyah frenk üzümü, sedir ağacı ve ipeksi tanenler.',
                'volume_ml' => 750,
                'alcohol_percentage' => 13.5,
                'taste_notes' => 'Menekşe, Siyah Frenk Üzümü, Sedir Ağacı, Kadife Tanen',
                'price' => 65000.00,
                'original_price' => 72000.00,
                'badge' => 'GRAND CRU',
                'is_featured' => true,
                'sort_order' => 51,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Sassicaia Tenuta San Guido Bolgheri',
                'sub_title' => 'Süper Toskana İkonu | İtalya 2019',
                'description' => 'Cabernet Sauvignon ve Cabernet Franc harmanı; yabani böğürtlen, adaçayı, tütün yaprağı ve mineral gövde.',
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'taste_notes' => 'Yabani Böğürtlen, Tütün Yaprağı, Adaçayı',
                'price' => 42000.00,
                'original_price' => 47000.00,
                'badge' => 'SUPER TUSCAN',
                'is_featured' => true,
                'sort_order' => 52,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Gaja Barbaresco DOCG',
                'sub_title' => 'Piedmont İtalya | %100 Nebbiolo',
                'description' => 'Kurutulmuş gül yaprakları, katran, yabani kiraz, trüf mantarı ve güçlü asidite dengesi.',
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'taste_notes' => 'Kurutulmuş Gül, Yabani Kiraz, Trüf Mantarı',
                'price' => 28000.00,
                'original_price' => 31000.00,
                'badge' => 'PIEDMONT ICON',
                'is_featured' => false,
                'sort_order' => 53,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Whispering Angel Rosé Côtes de Provence',
                'sub_title' => 'Château d\'Esclans | Provence Fransa',
                'description' => 'Fransız Rivierası rüzgarı; taze çilek, şeftali çiçeği ve kristal netliğinde ferahlatıcı mineralite.',
                'volume_ml' => 750,
                'alcohol_percentage' => 13.0,
                'taste_notes' => 'Taze Çilek, Şeftali Çiçeği, Kristal Asidite',
                'price' => 6500.00,
                'original_price' => 7500.00,
                'badge' => 'SUMMER ROSE',
                'is_featured' => false,
                'sort_order' => 54,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Chablis Premier Cru Domaine Laroche',
                'sub_title' => '%100 Chardonnay | Burgonya Fransa',
                'description' => 'Burgonya mineralitesi, yeşil elma, ıslak çakıl taşı ve kireçtaşı asiditesi ile beyaz şarap şaheseri.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Yeşil Elma, Kireçtaşı Minerali, Islak Taş',
                'price' => 9500.00,
                'original_price' => 11000.00,
                'badge' => 'CRISP WHITE',
                'is_featured' => false,
                'sort_order' => 55,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Tignanello Antinori Toscana IGT',
                'sub_title' => 'Sangiovese & Cabernet | Toskana',
                'description' => 'Meşe fıçılarda yıllanmış olgun erik, bitter kakao, baharat ve kadife pürüzsüzlükte tanen yapısı.',
                'volume_ml' => 750,
                'alcohol_percentage' => 14.0,
                'taste_notes' => 'Olgun Erik, Kakao, Vanilya, Baharat',
                'price' => 24000.00,
                'original_price' => 27000.00,
                'badge' => 'TUSCANY',
                'is_featured' => false,
                'sort_order' => 56,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Cloudy Bay Sauvignon Blanc Marlborough',
                'sub_title' => 'Yeni Zelanda | Efsanevi Beyaz Seçki',
                'description' => 'Çarkıfelek meyvesi, kivi, taze biçilmiş çimen ve canlı narenciye asiditesi sunan ferahlatıcı beyaz.',
                'volume_ml' => 750,
                'alcohol_percentage' => 13.0,
                'taste_notes' => 'Çarkıfelek Meyvesi, Kivi, Taze Çimen, Misket Limonu',
                'price' => 7800.00,
                'original_price' => 8900.00,
                'badge' => 'TROPICAL WHITE',
                'is_featured' => false,
                'sort_order' => 57,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Amarone della Valpolicella Masi Costasera',
                'sub_title' => 'Veneto İtalya | Kurutulmuş Üzüm Harmanı',
                'description' => 'Kurutulmuş üzümlerden üretilen tam gövdeli lezzet; kiraz reçeli, tarçın ve bitter çikolata zenginliği.',
                'volume_ml' => 750,
                'alcohol_percentage' => 15.0,
                'taste_notes' => 'Kiraz Reçeli, Tarçın, Kuru İncir, Yoğun Gövde',
                'price' => 16500.00,
                'original_price' => 19000.00,
                'badge' => 'FULL BODY',
                'is_featured' => false,
                'sort_order' => 58,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Santa Margherita Pinot Grigio Valdadige',
                'sub_title' => 'Trentino-Alto Adige | İtalya',
                'description' => 'Kuzey İtalya dağ eteklerinden taze armut, narenciye ve çıtır asidite ile hafif ve zarif beyaz şarap.',
                'volume_ml' => 750,
                'alcohol_percentage' => 12.5,
                'taste_notes' => 'Taze Armut, Narenciye, Çıtır Asidite',
                'price' => 5500.00,
                'original_price' => 6400.00,
                'badge' => 'CLASSIC WHITE',
                'is_featured' => false,
                'sort_order' => 59,
            ],
            [
                'category_id' => $catWine->id,
                'name' => 'Valdobbiadene Prosecco Superiore DOCG',
                'sub_title' => 'Millesimato Brut | Veneto İtalya',
                'description' => 'Altın elma, akasya çiçeği ve hafif bal notaları içeren ince kabarcıklı premium İtalyan köpüklüsü.',
                'volume_ml' => 750,
                'alcohol_percentage' => 11.5,
                'taste_notes' => 'Altın Elma, Akasya Çiçeği, İnce Kabarcıklar',
                'price' => 4800.00,
                'original_price' => 5500.00,
                'badge' => 'SPARKLING',
                'is_featured' => false,
                'sort_order' => 60,
            ],

            [
                'category_id' => $catHookah->id,
                'name' => 'Medusa Velvet Gold Special Hookah',
                'sub_title' => '24K Altın Kristal Takım & Özel Meyve Karışımı',
                'description' => '24K altın detaylı özel kristal takımda yabani böğürtlen, buzlu nane, tropikal guava ve gül esansı.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Yabani Böğürtlen, Buzlu Nane, Guava, Gül',
                'price' => 2200.00,
                'original_price' => 2600.00,
                'badge' => 'VIP SHISHA',
                'is_featured' => true,
                'sort_order' => 61,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Dark Leaf Russian Reserve Shisha',
                'sub_title' => 'Darkside & Musthave Koyu Yaprak Tütün',
                'description' => 'Premium Rus koyu tütünü, kavrulmuş İtalyan kahvesi, Bourbon vanilyası ve isli viski notası.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Kavrulmuş Kahve, Bourbon Vanilya, İsli Tütün',
                'price' => 1950.00,
                'original_price' => 2300.00,
                'badge' => 'DARK LEAF',
                'is_featured' => true,
                'sort_order' => 62,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Love 66 Midnight Glow Blend',
                'sub_title' => 'Karpuz, Kavun & Kristal Mentol',
                'description' => 'Tatlı karpuz, kokulu kavun, çarkıfelek meyvesi ve ferahlatıcı kristal mentol patlaması.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Karpuz, Kavun, Çarkıfelek, Buzlu Mentol',
                'price' => 1650.00,
                'original_price' => 1900.00,
                'badge' => 'POPULAR',
                'is_featured' => false,
                'sort_order' => 63,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Lady Killer Exotic Fusion',
                'sub_title' => 'Şeftali, Mango, Nane & Çilek',
                'description' => 'Tatlı şeftali, olgun mango, taze nane yaprakları ve dağ çileği ile yoğun duman performansı.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Şeftali, Mango, Dağ Çileği, Nane',
                'price' => 1650.00,
                'original_price' => 1900.00,
                'badge' => 'FRUITY',
                'is_featured' => false,
                'sort_order' => 64,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Blue Ice & Mountain Berry Shisha',
                'sub_title' => 'Yaban Mersini & Ekstra Soğutmalı Buz Marpuç',
                'description' => 'Taze yaban mersini, dağ böğürtleni ve buz haznesiyle kesintisiz soğuk duman deneyimi.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Yaban Mersini, Orman Meyveleri, Ekstra Buz',
                'price' => 1600.00,
                'original_price' => 1850.00,
                'badge' => 'EXTRA ICE',
                'is_featured' => false,
                'sort_order' => 65,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Spiced Chai & Vanilla Cream Shisha',
                'sub_title' => 'Kakule, Tarçın & Kremalı Vanilya',
                'description' => 'Kakule, tarçın çubuğu, karanfil ve kremalı Madagaskar vanilyası ile sıcak kış baharatı harmanı.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Kakule, Tarçın, Kremalı Vanilya',
                'price' => 1750.00,
                'original_price' => 2000.00,
                'badge' => 'WARM SPICE',
                'is_featured' => false,
                'sort_order' => 66,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Double Apple Royal Traditional',
                'sub_title' => 'Klasik Anason & Yeşil Elma Tütünü',
                'description' => 'Geleneksel anason ve tatlı yeşil elma harmanı; el yapımı toprak lülede yoğun lezzet.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Anason, Yeşil Elma, Geleneksel Duman',
                'price' => 1500.00,
                'original_price' => 1750.00,
                'badge' => 'TRADITIONAL',
                'is_featured' => false,
                'sort_order' => 67,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Citrus Mint Mojito Shisha Blend',
                'sub_title' => 'Misket Limonu, Taze Nane & Esmer Şeker',
                'description' => 'Taze limon, lime dilimleri, nane yaprakları ve hafif şeker kamışı notasıyla canlandırıcı lezzet.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Lime, Nane Yaprakları, Şeker Kamışı',
                'price' => 1600.00,
                'original_price' => 1850.00,
                'badge' => 'REFRESH',
                'is_featured' => false,
                'sort_order' => 68,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Grape Mint Frost Edition',
                'sub_title' => 'Siyah Üzüm & Dağ Nanesi',
                'description' => 'Siyah üzüm, nane yaprakları ve buz bazlı soğutmalı marpuç ile klasik lezzetin en ferah hali.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Siyah Üzüm, Dağ Nanesi, Buz',
                'price' => 1550.00,
                'original_price' => 1800.00,
                'badge' => 'CLASSIC',
                'is_featured' => false,
                'sort_order' => 69,
            ],
            [
                'category_id' => $catHookah->id,
                'name' => 'Pineapple Royal Fresh Fruit Bowl',
                'sub_title' => 'Oyulmuş Taze Ananas Lülesi & Tropikal Tütün',
                'description' => 'Gerçek oyulmuş ananas meyvesi lülesi üzerinde servis edilen tropikal meyve ve mango şöleni.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Taze Ananas Suyu, Mango, Tropikal Meyveler',
                'price' => 2500.00,
                'original_price' => 2900.00,
                'badge' => 'FRUIT BOWL',
                'is_featured' => true,
                'sort_order' => 70,
            ],

            [
                'category_id' => $catFood->id,
                'name' => 'Black Truffle & Parmesan Fries',
                'sub_title' => 'Taze Trüf Yağı & 24 Aylık Reggiano',
                'description' => 'Çıtır patates dilimleri, taze İtalyan trüf yağı, rendelenmiş Parmigiano Reggiano ve trüflü aioli dip sos.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Trüf Mantarı, 24 Aylık Parmesan, Sarımsaklı Aioli',
                'price' => 750.00,
                'original_price' => 850.00,
                'badge' => 'SNACK ICON',
                'is_featured' => false,
                'sort_order' => 71,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Wagyu Beef Sliders Trio (3 Adet)',
                'sub_title' => 'A5 Wagyu & Karamelize Soğan Reçeli',
                'description' => 'Mini brioche ekmeklerinde ızgara Wagyu köftesi, eritilmiş füme cheddar, trüf mayonez ve soğan reçeli.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'A5 Wagyu Eti, Füme Cheddar, Brioche, Trüf Mayo',
                'price' => 1450.00,
                'original_price' => 1650.00,
                'badge' => 'CHEF SPECIAL',
                'is_featured' => true,
                'sort_order' => 72,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Oscietra Caviar & Blinis Set (30g)',
                'sub_title' => 'Royal Oscietra Havyarı & Geleneksel Blini',
                'description' => '30g Royal Oscietra havyarı, ılık tereyağlı blini krepleri, crème fraîche, ince kıyılmış frenk soğanı ve sedef kaşık.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Tuzlu Tereyağlı Havyar, Crème Fraîche, Sıcak Blini',
                'price' => 6500.00,
                'original_price' => 7500.00,
                'badge' => 'ULTRA LUXURY',
                'is_featured' => true,
                'sort_order' => 73,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Crispy Rock Shrimp Tempura',
                'sub_title' => 'Baharatlı Yuzu Mayo & Kavrulmuş Susam',
                'description' => 'Çıtır tempura hamurunda kaya karidesleri, acılı yuzu mayonez kaplaması ve çıtır taze soğan.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Çıtır Karides, Baharatlı Yuzu Mayo, Susam',
                'price' => 980.00,
                'original_price' => 1150.00,
                'badge' => 'HOT SELLER',
                'is_featured' => false,
                'sort_order' => 74,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Artisan Cheese & Charcuterie Platter',
                'sub_title' => 'İthal İtalyan & Fransız Şarküteri Seçkisi',
                'description' => 'Trüflü gouda, Manchego, Gorgonzola, Bresaola, füme antrikot dilimleri, ceviz, kuru incir ve kraker.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Trüflü Gouda, Bresaola, Manchego, Kuru İncir',
                'price' => 1850.00,
                'original_price' => 2200.00,
                'badge' => 'SHARING',
                'is_featured' => false,
                'sort_order' => 75,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Salmon & Tuna Tartare Cones (4 Adet)',
                'sub_title' => 'Susamlı Çıtır Külah & Ponzu Sos',
                'description' => 'Çıtır wonton külahlarında marine Norveç somonu ve sarıkanat ton balığı tartarı, avokado püresi ve havyar.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Norveç Somonu, Ton Balığı, Avokado, Ponzu',
                'price' => 1100.00,
                'original_price' => 1300.00,
                'badge' => 'RAW BAR',
                'is_featured' => false,
                'sort_order' => 76,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Duck Confit Bao Buns (3 Adet)',
                'sub_title' => 'Ağır Ateşte Pişmiş Ördek & Hoisin',
                'description' => 'Buharda pişmiş pamuk bao ekmeğinde tiftiklenmiş konfi ördek eti, hoisin sos, taze salatalık ve taze kişniş.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Konfi Ördek, Hoisin Sos, Buharda Bao Ekmeği',
                'price' => 950.00,
                'original_price' => 1100.00,
                'badge' => 'ASIAN FUSION',
                'is_featured' => false,
                'sort_order' => 77,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Crispy Calamari Fritti',
                'sub_title' => 'Kurutulmuş Chili & Sarımsaklı Lime Aioli',
                'description' => 'Hafif ve çıtır kaplamalı taze kalamar halkaları, kurutulmuş chili pul biberi ve sarımsaklı misket limonu dip sos.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Çıtır Kalamar, Sarımsaklı Lime Aioli, Hafif Acı',
                'price' => 850.00,
                'original_price' => 980.00,
                'badge' => 'CRISPY',
                'is_featured' => false,
                'sort_order' => 78,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Premium Roasted Luxury Nuts Platter',
                'sub_title' => 'Tütsülenmiş Badem, Kaju, Pekan & Deniz Tuzu',
                'description' => 'Fırında özel baharatlar ve tütsü dumanıyla kavrulmuş badem, kaju fıstığı, pekan cevizi ve deniz tuzu harmanı.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Tütsülü Badem, Fırın Kaju, Pekan Cevizi',
                'price' => 550.00,
                'original_price' => 650.00,
                'badge' => 'TABLE SNACK',
                'is_featured' => false,
                'sort_order' => 79,
            ],
            [
                'category_id' => $catFood->id,
                'name' => 'Dark Chocolate Lava Fondant & 24K Gold',
                'sub_title' => '%70 Valrhona Sıcak Çikolata & Vanilyalı Dondurma',
                'description' => 'Akışkan sıcak Fransız Valrhona bitter çikolata keki, Bourbon vanilyalı dondurma ve 24K yenilebilir altın varak.',
                'volume_ml' => null,
                'alcohol_percentage' => 0.0,
                'taste_notes' => 'Akışkan Bitter Çikolata, Bourbon Vanilya, Altın Varak',
                'price' => 650.00,
                'original_price' => 780.00,
                'badge' => 'DESSERT',
                'is_featured' => false,
                'sort_order' => 80,
            ],
        ];

        foreach ($products as $item) {
            $item['slug'] = Str::slug($item['name']);
            Product::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
