SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '+03:00';

CREATE DATABASE IF NOT EXISTS `mikale_club` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `mikale_club`;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `role` varchar(50) NOT NULL DEFAULT 'reception',
  `remember_token` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES (1, 'Reception Desk', 'club@gmail.com', NULL, '$2y$12$GHpu0ajQ2adQlAMuLLtik..BpT6BLkZ0rw3ocEGIzJHtdHm7N8ING', 'KDV9DwZE3bUZ4w3wM4UA12exYM2fBGAMW19k1VyXB9mekfao6RVFNUlqavse', '2026-08-18 11:03:34', '2026-08-18 11:03:34');

DROP TABLE IF EXISTS `categories`;
CREATE TABLE `categories` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `icon_type` varchar(50) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_slug_unique` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (1, 'VIP Şampanya & Şişe Servisi', 'vip-sampanya-sise-servisi', 'champagne', 'Prestige Cuvée, vintage şampanyalar ve VIP masa şişe ritüelleri', 1, 1, '2026-08-15 11:22:53', '2026-08-19 11:47:34');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (2, 'İmza Kokteyller & Miksoloji', 'imza-kokteyller-miksoloji', 'cocktail', 'Usta miksolojistler tarafından hazırlanan artisan tütsülü ve altın dokunuşlu kokteyller', 2, 1, '2026-08-15 11:22:53', '2026-08-19 11:47:34');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (3, 'Single Malt & Nadir Viskiler', 'single-malt-nadir-viskiler', 'whisky', 'İskoç, Japon ve Amerikan damıtımevlerinden yıllanmış ve seçkin viskiler', 3, 1, '2026-08-15 11:22:53', '2026-08-15 11:22:53');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (4, 'Ultra-Premium İçkiler', 'ultra-premium-ickiler', 'spirit', 'Seçkin tekilalar, el yapımı cinler, rezerv votkalar ve yıllanmış konyaklar', 4, 1, '2026-08-15 11:22:53', '2026-08-15 11:22:53');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (5, 'Shot Tepsileri & Bomb Setleri', 'shot-tepsileri-bomb-setleri', 'shots', 'Masa enerjisini yükselten alevli shotlar, özel tepsiler ve parti ritüelleri', 5, 1, '2026-08-15 11:22:53', '2026-08-15 11:22:53');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (6, 'Lüks Şaraplar & Köpüklüler', 'luks-saraplar-kopukluler', 'wine', 'Bordeaux Grand Cru, Toskana ve seçkin dünya bağlarından seçkiler', 6, 1, '2026-08-15 11:22:53', '2026-08-15 11:22:53');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (7, 'Artisan VIP Nargile', 'artisan-vip-nargile', 'hookah', 'Koyu yaprak Rus tütünleri, taze meyve lüleleri ve özel kristal takımlar', 7, 1, '2026-08-15 11:22:53', '2026-08-15 11:22:53');
INSERT INTO `categories` (`id`, `name`, `slug`, `icon_type`, `description`, `sort_order`, `is_active`, `created_at`, `updated_at`) VALUES (8, 'VIP Lounge Atıştırmalıkları', 'vip-lounge-atistirmaliklari', 'food', 'Havyar, Wagyu slider, trüflü lezzetler ve gece tapasları', 8, 1, '2026-08-15 11:22:53', '2026-08-15 11:22:53');

DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `sub_title` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `volume_ml` int(11) DEFAULT NULL,
  `alcohol_percentage` decimal(4,1) DEFAULT NULL,
  `taste_notes` varchar(255) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `original_price` decimal(10,2) DEFAULT NULL,
  `currency` varchar(10) NOT NULL DEFAULT '₺',
  `badge` varchar(50) DEFAULT NULL,
  `is_featured` tinyint(1) NOT NULL DEFAULT 0,
  `is_available` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `products_slug_unique` (`slug`),
  KEY `products_category_id_foreign` (`category_id`),
  CONSTRAINT `products_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (1, 1, 'Dom Pérignon Vintage Brut', 'dom-perignon-vintage-brut', 'Vintage 2013 | Épernay Prestige Cuvée', 'Taze briyoş, beyaz şeftali, narenciye ve ipeksi mineral dokunuşlarla gecenin vazgeçilmez VIP ritüeli.', 750, 12.5, 'Taze Briyoş, Beyaz Şeftali, Kireçtaşı Minerali', 28500, 32000, '₺', 'VIP ICON', 1, 1, 2, '2026-08-15 11:23:08', '2026-08-19 11:35:39');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (2, 1, 'Armand de Brignac Ace of Spades Gold', 'armand-de-brignac-ace-of-spades-gold', 'Brut Gold | Altın Kaplama Özel Şişe', 'Kremalı tereyağı, pişmiş elma, vanilya ve pürüzsüz altın kabarcıklar içeren dünya çapında ikonik şampanya.', 750, 12.5, 'Pişmiş Elma, Vanilya Çubuğu, Tereyağlı Briyoş', 45000, 50000, '₺', 'PRESTIGE', 1, 1, 1, '2026-08-15 11:23:08', '2026-08-19 11:35:39');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (3, 1, 'Louis Roederer Cristal Brut', 'louis-roederer-cristal-brut', 'Millésimé 2014 | Düz Tabana Sahip Kristal Şişe', 'Beyaz çiçekler, kavrulmuş fındık, kireçtaşı mineralliği ve narin narenciye kabuğu zarafeti.', 750, 12, 'Akasya Çiçeği, Fındık, Narenciye Kabuğu', 42000, 46000, '₺', 'RARE', 1, 1, 3, '2026-08-15 11:23:08', '2026-08-19 11:32:28');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (4, 1, 'Moët & Chandon Impérial Brut', 'moet-chandon-imperial-brut', 'Brut Réserve | Fransa', 'Yeşil elma, sarı armut, narenciye tazeliği ve taze ceviz notalarıyla dengeli ve canlı bir kutlama içeceği.', 750, 12, 'Yeşil Elma, Armut, Taze Ceviz', 12500, 14000, '₺', 'BESTSELLER', 0, 1, 4, '2026-08-15 11:23:08', '2026-08-19 11:32:28');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (5, 1, 'Moët & Chandon Ice Impérial', 'moet-chandon-ice-imperial', 'Buz Üzerinde Servis Edilen Özel Seri', 'Buzla ve taze nane veya kırmızı meyvelerle servis edilen tropikal meyve, mango, guava ve zencefil harmanı.', 750, 12, 'Mango, Guava, Taze Zencefil, Nane', 14500, 16500, '₺', 'SUMMER VIP', 0, 1, 5, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (6, 1, 'Veuve Clicquot Yellow Label Brut', 'veuve-clicquot-yellow-label-brut', 'Reims | Güçlü Pinot Noir Hakimiyeti', 'Vanilya, olgun armut, kavrulmuş badem ve sağlam gövdesiyle gece clublarının klasik tercihi.', 750, 12, 'Kavrulmuş Badem, Olgun Armut, Vanilya', 13500, 15000, '₺', 'CLASSIC', 0, 1, 6, '2026-08-15 11:23:08', '2026-08-19 11:32:28');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (7, 1, 'Dom Pérignon Rosé Luminous', 'dom-perignon-rose-luminous', 'Karanlıkta Parlayan LED Tabanlı Özel Şişe', 'Yabani çilek, kuru incir ve füme baharat notaları içeren, masada parlayan lüks pembe şampanya.', 750, 12.5, 'Yabani Çilek, İncir, Füme Baharat', 48000, 54000, '₺', 'LUMINOUS', 1, 1, 7, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (8, 1, 'Krug Grande Cuvée 171st Edition', 'krug-grande-cuvee-171st-edition', '10 Farklı Yıldan 120 Şarabın Harmanı', 'Kavrulmuş badem, nuga, zencefilli kurabiye ve derin zenginlik sunan dünyanın en prestijli şampanyası.', 750, 12.5, 'Nuga, Zencefilli Kurabiye, Badem', 36000, 40000, '₺', 'CONNOISSEUR', 0, 1, 8, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (9, 1, 'Ruinart Blanc de Blancs', 'ruinart-blanc-de-blancs', '%100 Premier Cru Chardonnay', 'Dünyanın en eski şampanya evinden beyaz şeftali, yasemin çiçeği ve nane ferahlığıyla saf zarafet.', 750, 12.5, 'Beyaz Şeftali, Yasemin, Taze Nane', 18500, 21000, '₺', 'REFINED', 0, 1, 9, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (10, 1, 'Perrier-Jouët Belle Epoque Brut', 'perrier-jouet-belle-epoque-brut', 'Épernay | Çiçek Motifli Sanat Eseri Şişe', 'Akasya balı, taze zencefil ve beyaz erik aromalarıyla bezeli olağanüstü dengeli bir şampanya.', 750, 12.5, 'Akasya Balı, Beyaz Erik, Zencefil', 29500, 33000, '₺', 'EXCLUSIVE', 0, 1, 10, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (11, 2, 'Midnight Obsidian Smoke', 'midnight-obsidian-smoke', 'Tütsülü Mezkal & Aktif Karbon Reçetesi', 'İsli Oaxacan mezkali, aktif karbon likörü, taze lime suyu, organik agave ve tütsülenmiş biberiye dalı.', 220, 18.5, 'Tütsü, Biberiye, Taze Lime, İsli Agave', 950, 1100, '₺', 'SIGNATURE', 1, 1, 1, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (12, 2, 'Golden Velvet Royale', 'golden-velvet-royale', '24K Yenilebilir Altın Varaklı Şampanya Kokteyli', 'Hennessy VSOP konyak, passion fruit püresi, el yapımı vanilya şurubu ve Moët Brut şampanya köpüğü.', 200, 16, 'Çarkıfelek Meyvesi, Vanilya, Altın Köpük', 1100, 1300, '₺', 'LUXURY', 1, 1, 2, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (13, 2, 'Truffle Smoked Old Fashioned', 'truffle-smoked-old-fashioned', 'Trüf Mantarı İnfüzyonlu Meşe Dumanı', 'Woodford Reserve bourbon viski, trüf özü, organik akçaağaç şurubu, angostura ve kiraz dumanı.', 180, 28, 'Trüf Mantarı, Meşe Ağacı, Karamel, Portakal Kabuğu', 1050, 1200, '₺', 'CRAFT', 1, 1, 3, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (14, 2, 'Tokyo Sakura Cloud', 'tokyo-sakura-cloud', 'Roku Gin & Yuzu Sakura Köpüğü', 'Japon Gini Roku, liçi likörü, taze yuzu suyu ve kadifemsi sakura çayı aromalı moleküler köpük.', 220, 15.5, 'Sakura Çiçeği, Liçi, Yuzu Narenciyesi', 900, 1050, '₺', 'EXOTIC', 0, 1, 4, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (15, 2, 'Spicy Passion Dragon', 'spicy-passion-dragon', 'Chili İnfüzyonlu Reposado Tekila', 'Acı biber infüzyonlu tekila, taze çarkıfelek meyvesi, ejder meyvesi püresi ve tütsülü lav tuzu kenarı.', 240, 17, 'Chili Acılığı, Tropikal Passion, Lav Tuzu', 850, 950, '₺', 'POPULAR', 0, 1, 5, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (16, 2, 'Espresso Velvet Martini', 'espresso-velvet-martini', 'Single-Origin Etiyopya Espresso & Beluga', 'Beluga votka, taze çekilmiş single-origin espresso, Kahlúa kahve likörü ve Belçika bitter kakao tozu.', 180, 20, 'Koyu Espresso, Bitter Çikolata, İpeksi Krema', 850, 980, '₺', 'AFTER DARK', 0, 1, 7, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (17, 2, 'Basil & Cucumber Smash', 'basil-cucumber-smash', 'Hendrick\'s Gin & Mürver Çiçeği', 'Hendrick\'s cin, taze ezilmiş fesleğen yaprakları, salatalık şerbeti, St-Germain ve premium tonik.', 240, 14.5, 'Taze Fesleğen, Salatalık, Mürver Çiçeği', 800, 900, '₺', 'REFRESHING', 0, 1, 6, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (18, 2, 'Dark Nebula Blackberry Sour', 'dark-nebula-blackberry-sour', 'Böğürtlen & Burbon Kadife Köpük', 'Böğürtlen infüzyonlu viski, ev yapımı ekşi karışım, organik agave ve pürüzsüz vegan köpük tabakası.', 200, 17.5, 'Orman Meyveleri, Ekşi Narenciye, İpeksi Köpük', 880, 1000, '₺', 'SMOOTH', 0, 1, 8, '2026-08-15 11:23:08', '2026-08-19 11:34:48');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (19, 2, 'Coconut Cloud Negroni', 'coconut-cloud-negroni', 'Hindistan Cevizi Yağlı Campari & Tanqueray 10', 'Hindistan cevizi yağıyla yıkanmış Campari, Tanqueray No. Ten, tatlı kırmızı vermut ve portakal esansı.', 180, 24, 'Hindistan Cevizi, Acı-Tatlı Portakal, Botanik Ardıç', 920, 1050, '₺', 'TWIST', 0, 1, 10, '2026-08-15 11:23:08', '2026-08-19 11:35:20');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (20, 2, 'Royal French 75', 'royal-french-75', 'The Botanist Gin & Moët Brut Şampanya', 'The Botanist Islay cin, taze limon suyu, şeker kamışı şurubu ve üstüne eklenen Moët Brut şampanya.', 190, 16.5, 'Limon Çiçeği, Canlı Köpük, Botanik Zarafet', 980, 1150, '₺', 'ELEGANT', 0, 1, 9, '2026-08-15 11:23:08', '2026-08-19 11:35:20');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (21, 3, 'The Macallan 18 Double Cask', 'the-macallan-18-double-cask', 'Single Malt Scotch Whisky | Speyside', 'Kuru meyve, zencefil, vanilya, zengin meşe ve pürüzsüz portakal kabuğu notalarıyla viskinin zirvesi.', 700, 43, 'Kuru Meyve, Zencefil, Şeri Meşesi, Portakal Kabuğu', 32000, 36000, '₺', 'SINGLE MALT', 1, 1, 21, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (22, 3, 'The Macallan 12 Sherry Oak', 'the-macallan-12-sherry-oak', 'Single Malt Scotch Whisky | Jerez Cask', 'Kuru üzüm, tarçın, fındık ve zengin şeri fıçısı aromaları içeren ikonik İskoç lezzeti.', 700, 40, 'Kuru Üzüm, Tarçın, Şeri, Kavrulmuş Fındık', 14000, 16000, '₺', 'POPULAR', 0, 1, 22, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (23, 3, 'Yamazaki 12 Japanese Single Malt', 'yamazaki-12-japanese-single-malt', 'Suntory Whisky | Japonya', 'Mizunara Japon meşesi, şeftali, ananas, hindistan cevizi ve ipeksi uzun bitiş sunan nadir viski.', 700, 43, 'Mizunara Meşesi, Şeftali, Ananas, Sandal Ağacı', 34000, 39000, '₺', 'RARE JAPANESE', 1, 1, 23, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (24, 3, 'Hibiki Japanese Harmony', 'hibiki-japanese-harmony', 'Master\'s Blend | 24 Köşeli Özel Şişe', 'Gül yaprağı, liçi, biberiye, olgun meşe ve sandal ağacı zarafetini buluşturan Japon harmoni viskisi.', 700, 43, 'Gül, Liçi, Sandal Ağacı, Bal', 22000, 25000, '₺', 'HARMONY', 0, 1, 24, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (25, 3, 'Lagavulin 16 Islay Single Malt', 'lagavulin-16-islay-single-malt', '16 Years Old | Islay İskoçya', 'Yoğun turba dumanı, deniz tuzu, iyot, kuru meyve ve tatlı meşe fıçısı etkisiyle turba tutkunlarının gözdesi.', 700, 43, 'Yoğun Turba Dumanı, İyot, Deniz Tuzu, Kuru Meyve', 16500, 19000, '₺', 'SMOKY KING', 0, 1, 25, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (26, 3, 'Johnnie Walker Blue Label', 'johnnie-walker-blue-label', 'Rare Cask Blend | İskoçya', '10.000 fıçıdan sadece 1 tanesinin seçilmesiyle üretilen fındık, bal, gül ve ipeksi duman harmanı.', 700, 40, 'Bal, Fındık, Gül Yaprakları, İpeksi Duman', 24000, 27000, '₺', 'ICONIC', 0, 1, 26, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (27, 3, 'Glenfiddich 18 Small Batch', 'glenfiddich-18-small-batch', 'Oloroso Sherry & Bourbon Casks', 'Fırınlanmış elma, tarçın, kuru meyve ve sağlam İspanyol meşesi içeren 18 yıllık olgunlaşma.', 700, 40, 'Fırın Elma, Tarçın, İspanyol Meşesi', 15500, 17500, '₺', 'SMOOTH', 0, 1, 27, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (28, 3, 'Balvenie 14 Caribbean Cask', 'balvenie-14-caribbean-cask', 'Karayip Rom Fıçısında Bitiş', 'Karayip rom fıçılarında son dokunuşu yapılan tatlı tropikal meyve, vanilya ve tofi aromalı single malt.', 700, 43, 'Tropikal Meyve, Tofi, Sıcak Rom Baharatı', 16000, 18000, '₺', 'SPECIAL CASK', 0, 1, 28, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (29, 3, 'Talisker 10 Skye Single Malt', 'talisker-10-skye-single-malt', 'Made by the Sea | Isle of Skye', 'Deniz tuzu serpintisi, taze çekilmiş karabiber, kuru meyve ve volkanik duman karakteri.', 700, 45.8, 'Karabiber, Deniz Tuzu, Volkanik Duman', 11500, 13000, '₺', 'ISLAND', 0, 1, 29, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (30, 3, 'Woodford Reserve Double Oaked', 'woodford-reserve-double-oaked', 'Kentucky Straight Bourbon Whiskey', 'Çift fırınlanmış meşe fıçılarda dinlendirilen yoğun karamel, kavrulmuş fındık ve bitter çikolata notaları.', 700, 43.2, 'Karamel, Kavrulmuş Fındık, Bitter Çikolata', 11000, 12500, '₺', 'PREMIUM BOURBON', 0, 1, 30, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (31, 4, 'Clase Azul Reposado Tequila', 'clase-azul-reposado-tequila', 'El Yapımı İkonik Seramik Şişe', '%100 Blue Weber Agave, vanilya, fındık, pişmiş agave ve karamel zenginliği ile dünyanın en ünlü tekilası.', 700, 40, 'Vanilya, Fındık, Pişmiş Agave, Karamel', 38000, 42000, '₺', 'ULTRA VIP', 1, 1, 31, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (32, 4, 'Don Julio 1942 Añejo Tequila', 'don-julio-1942-anejo-tequila', 'Jalisco Meksika | 2.5 Yıl Dinlendirilmiş', 'Meşe fıçıda dinlendirilen sıcak meşe, vanilya, kavrulmuş agave ve meşe aromalarıyla club gecelerinin favorisi.', 700, 38, 'Sıcak Meşe, Vanilya, Kavrulmuş Agave', 36000, 40000, '₺', 'CELEBRITY CHOICE', 1, 1, 32, '2026-08-15 11:23:08', '2026-08-19 11:32:28');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (33, 4, 'Patrón El Cielo Tequila', 'patron-el-cielo-tequila', 'Dört Kez Damıtılmış Prestige Silver', 'Dört kez damıtılmış gümüş tekila, ultra pürüzsüz içim, narenciye tazeliği ve doğal agave tatlılığı.', 700, 40, 'Parlak Narenciye, Tatlı Agave, Kristal Saflık', 26000, 29000, '₺', 'PURE SILVER', 0, 1, 33, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (34, 4, 'Beluga Gold Line Vodka', 'beluga-gold-line-vodka', 'Özel Çekiçli Mühürlü Kutu', '90 gün dinlendirilmiş, pirinç ve yabani gül infüzyonlu ultra premium lüks votka deneyimi.', 700, 40, 'Pirinç Özü, Yabani Gül, Kadife Pürüzsüzlük', 19500, 22000, '₺', 'GOLD LINE', 0, 1, 34, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (35, 4, 'Grey Goose VX Exceptional Vodka', 'grey-goose-vx-exceptional-vodka', 'Fransız Konyak Damlaları ile Zenginleştirilmiş', 'Fransız buğday votkasının nadir Grand Champagne konyak damlalarıyla harmanlandığı lüks şişe.', 1000, 40, 'Konyak Nüansı, Erik, Beyaz Meyve, İpek Doku', 14500, 16500, '₺', 'FRENCH LUXURY', 0, 1, 35, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (36, 4, 'Belvedere 10 Rare Single Estate', 'belvedere-10-rare-single-estate', '10 Adımlık Üretim & Elmas Kesim Şişe', 'Tek bir hasattan elde edilen organik elmas çavdarı, bal, yeşil elma ve kremsi doku.', 700, 40, 'Yeşil Elma, Bal, Vanilya Kreması', 22000, 25000, '₺', 'LIMITED', 0, 1, 36, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (37, 4, 'Monkey 47 Schwarzwald Dry Gin', 'monkey-47-schwarzwald-dry-gin', 'Almanya Kara Orman | 47 Botanik', 'Kara Orman kaynak suyu ve 47 farklı botanik bitki, ardıç, böğürtlen, limon otu ve egzotik baharatlar.', 500, 47, 'Ardıç, Böğürtlen, Limon Otu, Çam Esansı', 8500, 9500, '₺', 'BOTANICAL', 0, 1, 37, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (38, 4, 'The Botanist Islay Dry Gin', 'the-botanist-islay-dry-gin', 'Islay İskoçya | 22 Yabani Ada Bitkisi', 'Islay adasından elle toplanan 22 yabani ada bitkisiyle damıtılmış çiçeksi ve tazeleyici cin.', 700, 46, 'Yabani Nane, Papatya, Ardıç, Narenciye', 9500, 11000, '₺', 'ARTISAN', 0, 1, 38, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (39, 4, 'Zacapa 23 Solera Gran Reserva', 'zacapa-23-solera-gran-reserva', 'Guatemala | Deniz Seviyesinden 2300m Yüksekte', 'Solera sistemiyle yıllandırılmış bal, karamel, kurutulmuş meyve, meşe ve kakao zenginliği.', 700, 40, 'Karamel, Kuru İncir, Kakao, Meşe', 13500, 15000, '₺', 'SOLERA RUM', 0, 1, 39, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (40, 4, 'Hennessy XO Extra Old Cognac', 'hennessy-xo-extra-old-cognac', '100 Farklı Eaux-de-Vie Harmanı', 'Karabiber, kuru incir, kakao, tütün yaprağı ve deri dokunuşlarıyla efsanevi Fransız konyak başyapıtı.', 700, 40, 'Karabiber, Kuru İncir, Kakao, Deri', 28000, 32000, '₺', 'PRESTIGE COGNAC', 1, 1, 40, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (41, 5, 'Golden Tequila VIP Tray (6 Shots)', 'golden-tequila-vip-tray-6-shots', '6 Adet Don Julio Blanco & Altın Tuzu', 'Don Julio Blanco, tuzlanmış 24K altın pulları, taze portakal ve tarçın dilimleri ile servis edilen VIP tepsi.', 240, 38, 'Saf Agave, Tarçınlı Portakal, Altın Tuzu', 2400, 2800, '₺', 'PARTY TRAY', 1, 1, 41, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (42, 5, 'B-52 Flaming Layered Shots (4 Shots)', 'b-52-flaming-layered-shots-4-shots', '4 Adet 3 Katmanlı Alevli Shot', 'Kahlúa kahve likörü, Baileys Irish Cream ve Grand Marnier ile 3 katmanlı alevli shot seremonisi.', 160, 28, 'Kahve, Krema, Portakal Likörü, Karamel', 1800, 2100, '₺', 'FLAMING', 0, 1, 42, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (43, 5, 'Jägerbomb Energy Blast Set (4 Shots)', 'jagerbomb-energy-blast-set-4-shots', '4 Adet Jägermeister & Red Bull', 'Orijinal Jägermeister shot kadehinin buz gibi Red Bull kadehine bırakıldığı yüksek enerjili club klasiği.', 360, 25, 'Bitkisel Baharatlar, Enerji, Anason, Narenciye', 1900, 2200, '₺', 'HIGH ENERGY', 1, 1, 43, '2026-08-15 11:23:08', '2026-08-19 11:32:28');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (44, 5, 'Kamikaze Citrus Burst Tray (6 Shots)', 'kamikaze-citrus-burst-tray-6-shots', '6 Adet Votka & Cointreau Shot', 'Premium votka, Cointreau portakal likörü ve taze sıkılmış misket limonu suyu ile buz gibi ferahlık.', 240, 22, 'Misket Limonu, Portakal Kabuğu, Canlı Asidite', 1950, 2300, '₺', 'CRISP', 0, 1, 44, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (45, 5, 'Silver Bullet Mezcal Tray (6 Shots)', 'silver-bullet-mezcal-tray-6-shots', '6 Adet Tütsülü Mezkal & Passion', 'Oaxacan tütsülü mezkal, tütsülü lav tuzu ve taze çarkıfelek meyvesi dilimleri eşliğinde servis.', 240, 40, 'Tütsü Dumanı, Çarkıfelek Meyvesi, Lav Tuzu', 2600, 3000, '₺', 'SMOKY SHOTS', 0, 1, 45, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (46, 5, 'Lemon Drop Sugar Rim Set (6 Shots)', 'lemon-drop-sugar-rim-set-6-shots', '6 Adet Şeker Kenarlı Limon Shot', 'Absolut Citron votka, Limoncello, karamelize esmer şeker kenarlığı ve taze narenciye dilimi.', 240, 20, 'Tatlı Limon Şekeri, Taze Narenciye', 1850, 2100, '₺', 'SWEET & SOUR', 0, 1, 46, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (47, 5, 'Brain Hemorrhage Visual Set (4 Shots)', 'brain-hemorrhage-visual-set-4-shots', '4 Adet Görsel Efektli Katman Shot', 'Şeftali schnapps üzerine Baileys krema damlaları ve kan kırmızısı grenadin damlatılarak hazırlanan görsel şov.', 160, 18, 'Şeftali, İrlanda Kreması, Tatlı Nar', 1700, 2000, '₺', 'VISUAL EFFECT', 0, 1, 47, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (48, 5, 'Black Absinthe Devil Tray (4 Shots)', 'black-absinthe-devil-tray-4-shots', '4 Adet Siyah Absent & Alevli Şeker', '%55 alkollü siyah pelin otu absenti, anason esansı ve kaşıkta alevle karamelize edilmiş kesme şeker.', 160, 55, 'Güçlü Anason, Pelin Otu, Karamelize Şeker', 2800, 3200, '₺', 'EXTREME', 0, 1, 48, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (49, 5, 'Baby Guinness Mini Stout (6 Shots)', 'baby-guinness-mini-stout-6-shots', '6 Adet Kahve & Krema Mini Stout', 'Tía María kahve likörü üzerine dökülen Baileys krema köpüğü ile minyatür siyah bira görünümü.', 240, 20, 'Yoğun Kahve, İpeksi Krema, Vanilya', 1900, 2200, '₺', 'CREAMY', 0, 1, 49, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (50, 5, 'Godfather Nightcap Tray (4 Shots)', 'godfather-nightcap-tray-4-shots', '4 Adet İskoç Viskisi & Disaronno', 'Single malt İskoç viskisi ve otantik İtalyan badem likörü Disaronno ile güçlü ve tatlı shot ritüeli.', 160, 32, 'İskoç Meşesi, Acıbadem, Kayısı Çekirdeği', 1950, 2300, '₺', 'STRONG', 0, 1, 50, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (51, 6, 'Château Margaux Premier Grand Cru', 'chateau-margaux-premier-grand-cru', 'Bordeaux Margaux | Fransa 2015', 'Bordeaux\'nun efsanevi başyapıtı; menekşe çiçeği, siyah frenk üzümü, sedir ağacı ve ipeksi tanenler.', 750, 13.5, 'Menekşe, Siyah Frenk Üzümü, Sedir Ağacı, Kadife Tanen', 65000, 72000, '₺', 'GRAND CRU', 1, 1, 51, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (52, 6, 'Sassicaia Tenuta San Guido Bolgheri', 'sassicaia-tenuta-san-guido-bolgheri', 'Süper Toskana İkonu | İtalya 2019', 'Cabernet Sauvignon ve Cabernet Franc harmanı; yabani böğürtlen, adaçayı, tütün yaprağı ve mineral gövde.', 750, 14, 'Yabani Böğürtlen, Tütün Yaprağı, Adaçayı', 42000, 47000, '₺', 'SUPER TUSCAN', 1, 1, 52, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (53, 6, 'Gaja Barbaresco DOCG', 'gaja-barbaresco-docg', 'Piedmont İtalya | %100 Nebbiolo', 'Kurutulmuş gül yaprakları, katran, yabani kiraz, trüf mantarı ve güçlü asidite dengesi.', 750, 14, 'Kurutulmuş Gül, Yabani Kiraz, Trüf Mantarı', 28000, 31000, '₺', 'PIEDMONT ICON', 0, 1, 53, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (54, 6, 'Whispering Angel Rosé Côtes de Provence', 'whispering-angel-rose-cotes-de-provence', 'Château d\'Esclans | Provence Fransa', 'Fransız Rivierası rüzgarı; taze çilek, şeftali çiçeği ve kristal netliğinde ferahlatıcı mineralite.', 750, 13, 'Taze Çilek, Şeftali Çiçeği, Kristal Asidite', 6500, 7500, '₺', 'SUMMER ROSE', 0, 1, 54, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (55, 6, 'Chablis Premier Cru Domaine Laroche', 'chablis-premier-cru-domaine-laroche', '%100 Chardonnay | Burgonya Fransa', 'Burgonya mineralitesi, yeşil elma, ıslak çakıl taşı ve kireçtaşı asiditesi ile beyaz şarap şaheseri.', 750, 12.5, 'Yeşil Elma, Kireçtaşı Minerali, Islak Taş', 9500, 11000, '₺', 'CRISP WHITE', 0, 1, 55, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (56, 6, 'Tignanello Antinori Toscana IGT', 'tignanello-antinori-toscana-igt', 'Sangiovese & Cabernet | Toskana', 'Meşe fıçılarda yıllanmış olgun erik, bitter kakao, baharat ve kadife pürüzsüzlükte tanen yapısı.', 750, 14, 'Olgun Erik, Kakao, Vanilya, Baharat', 24000, 27000, '₺', 'TUSCANY', 0, 1, 56, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (57, 6, 'Cloudy Bay Sauvignon Blanc Marlborough', 'cloudy-bay-sauvignon-blanc-marlborough', 'Yeni Zelanda | Efsanevi Beyaz Seçki', 'Çarkıfelek meyvesi, kivi, taze biçilmiş çimen ve canlı narenciye asiditesi sunan ferahlatıcı beyaz.', 750, 13, 'Çarkıfelek Meyvesi, Kivi, Taze Çimen, Misket Limonu', 7800, 8900, '₺', 'TROPICAL WHITE', 0, 1, 57, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (58, 6, 'Amarone della Valpolicella Masi Costasera', 'amarone-della-valpolicella-masi-costasera', 'Veneto İtalya | Kurutulmuş Üzüm Harmanı', 'Kurutulmuş üzümlerden üretilen tam gövdeli lezzet; kiraz reçeli, tarçın ve bitter çikolata zenginliği.', 750, 15, 'Kiraz Reçeli, Tarçın, Kuru İncir, Yoğun Gövde', 16500, 19000, '₺', 'FULL BODY', 0, 1, 58, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (59, 6, 'Santa Margherita Pinot Grigio Valdadige', 'santa-margherita-pinot-grigio-valdadige', 'Trentino-Alto Adige | İtalya', 'Kuzey İtalya dağ eteklerinden taze armut, narenciye ve çıtır asidite ile hafif ve zarif beyaz şarap.', 750, 12.5, 'Taze Armut, Narenciye, Çıtır Asidite', 5500, 6400, '₺', 'CLASSIC WHITE', 0, 1, 59, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (60, 6, 'Valdobbiadene Prosecco Superiore DOCG', 'valdobbiadene-prosecco-superiore-docg', 'Millesimato Brut | Veneto İtalya', 'Altın elma, akasya çiçeği ve hafif bal notaları içeren ince kabarcıklı premium İtalyan köpüklüsü.', 750, 11.5, 'Altın Elma, Akasya Çiçeği, İnce Kabarcıklar', 4800, 5500, '₺', 'SPARKLING', 0, 1, 60, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (61, 7, 'Medusa Velvet Gold Special Hookah', 'medusa-velvet-gold-special-hookah', '24K Altın Kristal Takım & Özel Meyve Karışımı', '24K altın detaylı özel kristal takımda yabani böğürtlen, buzlu nane, tropikal guava ve gül esansı.', NULL, 0, 'Yabani Böğürtlen, Buzlu Nane, Guava, Gül', 2200, 2600, '₺', 'VIP SHISHA', 1, 1, 61, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (62, 7, 'Dark Leaf Russian Reserve Shisha', 'dark-leaf-russian-reserve-shisha', 'Darkside & Musthave Koyu Yaprak Tütün', 'Premium Rus koyu tütünü, kavrulmuş İtalyan kahvesi, Bourbon vanilyası ve isli viski notası.', NULL, 0, 'Kavrulmuş Kahve, Bourbon Vanilya, İsli Tütün', 1950, 2300, '₺', 'DARK LEAF', 1, 1, 62, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (63, 7, 'Love 66 Midnight Glow Blend', 'love-66-midnight-glow-blend', 'Karpuz, Kavun & Kristal Mentol', 'Tatlı karpuz, kokulu kavun, çarkıfelek meyvesi ve ferahlatıcı kristal mentol patlaması.', NULL, 0, 'Karpuz, Kavun, Çarkıfelek, Buzlu Mentol', 1650, 1900, '₺', 'POPULAR', 0, 1, 63, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (64, 7, 'Lady Killer Exotic Fusion', 'lady-killer-exotic-fusion', 'Şeftali, Mango, Nane & Çilek', 'Tatlı şeftali, olgun mango, taze nane yaprakları ve dağ çileği ile yoğun duman performansı.', NULL, 0, 'Şeftali, Mango, Dağ Çileği, Nane', 1650, 1900, '₺', 'FRUITY', 0, 1, 64, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (65, 7, 'Blue Ice & Mountain Berry Shisha', 'blue-ice-mountain-berry-shisha', 'Yaban Mersini & Ekstra Soğutmalı Buz Marpuç', 'Taze yaban mersini, dağ böğürtleni ve buz haznesiyle kesintisiz soğuk duman deneyimi.', NULL, 0, 'Yaban Mersini, Orman Meyveleri, Ekstra Buz', 1600, 1850, '₺', 'EXTRA ICE', 0, 1, 65, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (66, 7, 'Spiced Chai & Vanilla Cream Shisha', 'spiced-chai-vanilla-cream-shisha', 'Kakule, Tarçın & Kremalı Vanilya', 'Kakule, tarçın çubuğu, karanfil ve kremalı Madagaskar vanilyası ile sıcak kış baharatı harmanı.', NULL, 0, 'Kakule, Tarçın, Kremalı Vanilya', 1750, 2000, '₺', 'WARM SPICE', 0, 1, 66, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (67, 7, 'Double Apple Royal Traditional', 'double-apple-royal-traditional', 'Klasik Anason & Yeşil Elma Tütünü', 'Geleneksel anason ve tatlı yeşil elma harmanı; el yapımı toprak lülede yoğun lezzet.', NULL, 0, 'Anason, Yeşil Elma, Geleneksel Duman', 1500, 1750, '₺', 'TRADITIONAL', 0, 1, 67, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (68, 7, 'Citrus Mint Mojito Shisha Blend', 'citrus-mint-mojito-shisha-blend', 'Misket Limonu, Taze Nane & Esmer Şeker', 'Taze limon, lime dilimleri, nane yaprakları ve hafif şeker kamışı notasıyla canlandırıcı lezzet.', NULL, 0, 'Lime, Nane Yaprakları, Şeker Kamışı', 1600, 1850, '₺', 'REFRESH', 0, 1, 68, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (69, 7, 'Grape Mint Frost Edition', 'grape-mint-frost-edition', 'Siyah Üzüm & Dağ Nanesi', 'Siyah üzüm, nane yaprakları ve buz bazlı soğutmalı marpuç ile klasik lezzetin en ferah hali.', NULL, 0, 'Siyah Üzüm, Dağ Nanesi, Buz', 1550, 1800, '₺', 'CLASSIC', 0, 1, 69, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (70, 7, 'Pineapple Royal Fresh Fruit Bowl', 'pineapple-royal-fresh-fruit-bowl', 'Oyulmuş Taze Ananas Lülesi & Tropikal Tütün', 'Gerçek oyulmuş ananas meyvesi lülesi üzerinde servis edilen tropikal meyve ve mango şöleni.', NULL, 0, 'Taze Ananas Suyu, Mango, Tropikal Meyveler', 2500, 2900, '₺', 'FRUIT BOWL', 1, 1, 70, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (71, 8, 'Black Truffle & Parmesan Fries', 'black-truffle-parmesan-fries', 'Taze Trüf Yağı & 24 Aylık Reggiano', 'Çıtır patates dilimleri, taze İtalyan trüf yağı, rendelenmiş Parmigiano Reggiano ve trüflü aioli dip sos.', NULL, 0, 'Trüf Mantarı, 24 Aylık Parmesan, Sarımsaklı Aioli', 750, 850, '₺', 'SNACK ICON', 0, 1, 71, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (72, 8, 'Wagyu Beef Sliders Trio (3 Adet)', 'wagyu-beef-sliders-trio-3-adet', 'A5 Wagyu & Karamelize Soğan Reçeli', 'Mini brioche ekmeklerinde ızgara Wagyu köftesi, eritilmiş füme cheddar, trüf mayonez ve soğan reçeli.', NULL, 0, 'A5 Wagyu Eti, Füme Cheddar, Brioche, Trüf Mayo', 1450, 1650, '₺', 'CHEF SPECIAL', 1, 1, 72, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (73, 8, 'Oscietra Caviar & Blinis Set (30g)', 'oscietra-caviar-blinis-set-30g', 'Royal Oscietra Havyarı & Geleneksel Blini', '30g Royal Oscietra havyarı, ılık tereyağlı blini krepleri, crème fraîche, ince kıyılmış frenk soğanı ve sedef kaşık.', NULL, 0, 'Tuzlu Tereyağlı Havyar, Crème Fraîche, Sıcak Blini', 6500, 7500, '₺', 'ULTRA LUXURY', 1, 1, 73, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (74, 8, 'Crispy Rock Shrimp Tempura', 'crispy-rock-shrimp-tempura', 'Baharatlı Yuzu Mayo & Kavrulmuş Susam', 'Çıtır tempura hamurunda kaya karidesleri, acılı yuzu mayonez kaplaması ve çıtır taze soğan.', NULL, 0, 'Çıtır Karides, Baharatlı Yuzu Mayo, Susam', 980, 1150, '₺', 'HOT SELLER', 0, 1, 74, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (75, 8, 'Artisan Cheese & Charcuterie Platter', 'artisan-cheese-charcuterie-platter', 'İthal İtalyan & Fransız Şarküteri Seçkisi', 'Trüflü gouda, Manchego, Gorgonzola, Bresaola, füme antrikot dilimleri, ceviz, kuru incir ve kraker.', NULL, 0, 'Trüflü Gouda, Bresaola, Manchego, Kuru İncir', 1850, 2200, '₺', 'SHARING', 0, 1, 75, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (76, 8, 'Salmon & Tuna Tartare Cones (4 Adet)', 'salmon-tuna-tartare-cones-4-adet', 'Susamlı Çıtır Külah & Ponzu Sos', 'Çıtır wonton külahlarında marine Norveç somonu ve sarıkanat ton balığı tartarı, avokado püresi ve havyar.', NULL, 0, 'Norveç Somonu, Ton Balığı, Avokado, Ponzu', 1100, 1300, '₺', 'RAW BAR', 0, 1, 76, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (77, 8, 'Duck Confit Bao Buns (3 Adet)', 'duck-confit-bao-buns-3-adet', 'Ağır Ateşte Pişmiş Ördek & Hoisin', 'Buharda pişmiş pamuk bao ekmeğinde tiftiklenmiş konfi ördek eti, hoisin sos, taze salatalık ve taze kişniş.', NULL, 0, 'Konfi Ördek, Hoisin Sos, Buharda Bao Ekmeği', 950, 1100, '₺', 'ASIAN FUSION', 0, 1, 77, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (78, 8, 'Crispy Calamari Fritti', 'crispy-calamari-fritti', 'Kurutulmuş Chili & Sarımsaklı Lime Aioli', 'Hafif ve çıtır kaplamalı taze kalamar halkaları, kurutulmuş chili pul biberi ve sarımsaklı misket limonu dip sos.', NULL, 0, 'Çıtır Kalamar, Sarımsaklı Lime Aioli, Hafif Acı', 850, 980, '₺', 'CRISPY', 0, 1, 78, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (79, 8, 'Premium Roasted Luxury Nuts Platter', 'premium-roasted-luxury-nuts-platter', 'Tütsülenmiş Badem, Kaju, Pekan & Deniz Tuzu', 'Fırında özel baharatlar ve tütsü dumanıyla kavrulmuş badem, kaju fıstığı, pekan cevizi ve deniz tuzu harmanı.', NULL, 0, 'Tütsülü Badem, Fırın Kaju, Pekan Cevizi', 550, 650, '₺', 'TABLE SNACK', 0, 1, 79, '2026-08-15 11:23:08', '2026-08-15 11:23:08');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sub_title`, `description`, `volume_ml`, `alcohol_percentage`, `taste_notes`, `price`, `original_price`, `currency`, `badge`, `is_featured`, `is_available`, `sort_order`, `created_at`, `updated_at`) VALUES (80, 8, 'Dark Chocolate Lava Fondant & 24K Gold', 'dark-chocolate-lava-fondant-24k-gold', '%70 Valrhona Sıcak Çikolata & Vanilyalı Dondurma', 'Akışkan sıcak Fransız Valrhona bitter çikolata keki, Bourbon vanilyalı dondurma ve 24K yenilebilir altın varak.', NULL, 0, 'Akışkan Bitter Çikolata, Bourbon Vanilya, Altın Varak', 650, 780, '₺', 'DESSERT', 0, 1, 80, '2026-08-15 11:23:08', '2026-08-15 11:23:08');

DROP TABLE IF EXISTS `club_tables`;
CREATE TABLE `club_tables` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `table_number` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `section` varchar(100) NOT NULL,
  `capacity` int(11) NOT NULL DEFAULT 4,
  `qr_token` varchar(64) NOT NULL,
  `token_expires_at` timestamp NULL DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'available',
  `current_guest_count` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `club_tables_table_number_unique` (`table_number`),
  UNIQUE KEY `club_tables_qr_token_unique` (`qr_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (1, 'VIP-01', 'Royal VIP Suite 1', 'VIP Lounge', 'qr-vip-01-bFhi5uIV', 8, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (2, 'VIP-02', 'Royal VIP Suite 2', 'VIP Lounge', 'qr-vip-02-Poj63TiX', 8, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (3, 'VIP-03', 'Diamond VIP Table 3', 'VIP Lounge', 'qr-vip-03-5elMNkIR', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (4, 'VIP-04', 'Diamond VIP Table 4', 'VIP Lounge', 'qr-vip-04-YZszjGG4', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (5, 'VIP-05', 'Black Box VIP 5', 'VIP Lounge', 'qr-vip-05-NqkxioFe', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (6, 'VIP-06', 'Black Box VIP 6', 'VIP Lounge', 'qr-vip-06-RCyjOVre', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (7, 'T-01', 'Dancefloor High Table 1', 'Main Floor', 'qr-t-01-q1Tl8Uo1', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (8, 'T-02', 'Dancefloor High Table 2', 'Main Floor', 'qr-t-02-b2n1q93L', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (9, 'T-03', 'Dancefloor High Table 3', 'Main Floor', 'qr-t-03-0JbStiJX', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (10, 'T-04', 'Dancefloor High Table 4', 'Main Floor', 'qr-t-04-08g553Tp', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (11, 'T-05', 'DJ Front Table 5', 'Main Floor', 'qr-t-05-HE8FTRjV', 5, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (12, 'T-06', 'DJ Front Table 6', 'Main Floor', 'qr-t-06-gv3FHTFh', 5, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (13, 'T-07', 'Club Center Table 7', 'Main Floor', 'qr-t-07-PsrJ0b3t', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (14, 'T-08', 'Club Center Table 8', 'Main Floor', 'qr-t-08-xPG4q2Dl', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (15, 'TR-01', 'Sky Terrace Lounge 1', 'Terrace & Rooftop', 'qr-tr-01-8pDY2b6a', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (16, 'TR-02', 'Sky Terrace Lounge 2', 'Terrace & Rooftop', 'qr-tr-02-3MJiFAwR', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (17, 'TR-03', 'Terrace View Table 3', 'Terrace & Rooftop', 'qr-tr-03-3g8TBlD9', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (18, 'TR-04', 'Terrace View Table 4', 'Terrace & Rooftop', 'qr-tr-04-pFibulYi', 4, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (19, 'TR-05', 'Garden Cabana 5', 'Terrace & Rooftop', 'qr-tr-05-xKkdJvDc', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (20, 'TR-06', 'Garden Cabana 6', 'Terrace & Rooftop', 'qr-tr-06-o45Pj7dI', 6, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (21, 'BAR-01', 'Cocktail Bar Station 1', 'Cocktail Bar', 'qr-bar-01-lLJ4H4PO', 2, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (22, 'BAR-02', 'Cocktail Bar Station 2', 'Cocktail Bar', 'qr-bar-02-SGUmkcMa', 2, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (23, 'BAR-03', 'Cocktail Bar Station 3', 'Cocktail Bar', 'qr-bar-03-8MciUxLQ', 2, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');
INSERT INTO `club_tables` (`id`, `table_number`, `name`, `section`, `qr_token`, `capacity`, `is_active`, `created_at`, `updated_at`, `token_expires_at`) VALUES (24, 'BAR-04', 'Cocktail Bar Station 4', 'Cocktail Bar', 'qr-bar-04-ykvtITA1', 2, 1, '2026-08-15 11:23:08', '2026-08-19 11:27:09', '2026-08-26 11:27:09');

DROP TABLE IF EXISTS `club_guests`;
CREATE TABLE `club_guests` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `guest_code` varchar(50) NOT NULL,
  `name` varchar(255) NOT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `club_table_id` bigint(20) UNSIGNED DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'active',
  `check_in_at` timestamp NULL DEFAULT NULL,
  `check_out_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `club_guests_guest_code_unique` (`guest_code`),
  KEY `club_guests_club_table_id_foreign` (`club_table_id`),
  CONSTRAINT `club_guests_club_table_id_foreign` FOREIGN KEY (`club_table_id`) REFERENCES `club_tables` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `club_guests` (`id`, `guest_code`, `name`, `phone`, `club_table_id`, `status`, `check_in_at`, `check_out_at`, `created_at`, `updated_at`) VALUES (9, 'VIP-XLAR', 'Kemal Polat Yalçın', 05338724338, 21, 'active', '2026-08-19 11:39:24', NULL, '2026-08-19 11:39:24', '2026-08-19 11:52:03');

DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_number` varchar(50) NOT NULL,
  `club_table_id` bigint(20) UNSIGNED NOT NULL,
  `club_guest_id` bigint(20) UNSIGNED DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'pending',
  `total_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `currency` varchar(10) NOT NULL DEFAULT '₺',
  `notes` text DEFAULT NULL,
  `order_time` timestamp NOT NULL DEFAULT current_timestamp(),
  `prepared_time` timestamp NULL DEFAULT NULL,
  `served_time` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `orders_order_number_unique` (`order_number`),
  KEY `orders_club_table_id_foreign` (`club_table_id`),
  KEY `orders_club_guest_id_foreign` (`club_guest_id`),
  CONSTRAINT `orders_club_table_id_foreign` FOREIGN KEY (`club_table_id`) REFERENCES `club_tables` (`id`) ON DELETE CASCADE,
  CONSTRAINT `orders_club_guest_id_foreign` FOREIGN KEY (`club_guest_id`) REFERENCES `club_guests` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE `order_items` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) UNSIGNED NOT NULL,
  `product_id` bigint(20) UNSIGNED NOT NULL,
  `quantity` int(11) NOT NULL DEFAULT 1,
  `unit_price` decimal(10,2) NOT NULL,
  `total_price` decimal(10,2) NOT NULL,
  `special_notes` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `order_items_order_id_foreign` (`order_id`),
  KEY `order_items_product_id_foreign` (`product_id`),
  CONSTRAINT `order_items_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
  CONSTRAINT `order_items_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (1, '0001_01_01_000000_create_users_table', 1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (2, '0001_01_01_000001_create_cache_table', 1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (3, '0001_01_01_000002_create_jobs_table', 1);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (4, '2026_08_14_000001_create_club_tables_table', 2);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (5, '2026_08_14_000002_create_club_guests_table', 2);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (6, '2026_08_14_000003_create_categories_table', 2);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (7, '2026_08_14_000004_create_products_table', 2);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (8, '2026_08_14_000005_create_orders_table', 2);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (9, '2026_08_14_000006_create_order_items_table', 2);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (10, '2026_08_14_000007_create_bills_table', 2);
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES (11, '2026_08_19_000001_add_token_expires_at_to_club_tables_table', 3);

SET FOREIGN_KEY_CHECKS = 1;
